### ISSUE TITLE
Tag ShioRamen release commits

### ISSUE THREAD

**Issue by hatfieldbrian** [RamenDR/ShioRamen#69]
- [x] choose labeling/versioning scheme:
   - example: `shio-v0.1.0` where
   - the _first_ `0` is the release version
   - the `1` is the feature? version
   - the _second_ `0` is the maintenance version (for bug fixes)
- [x] choose commit to label as "first" release:
   - just choose tip of main whenever you do it; we can fix bugs
- [x] communicate tag's presence to Fusion team

**Comment by tjanssen3** [comment]
This process doesn't have a pull request associated with it, but the documentation for the full process is [here](https://git-scm.com/book/en/v2/Git-Basics-Tagging).

I used commit `ba4c8a6465a5bc909f09198f4c9447f0164c448b` because GitHub showed it as the most recent commit on `main` to pass the automated tests. Tag info below:

```bash
git tag -a shio-v0.1.0 ba4c8a6465a5bc909f09198f4c9447f0164c448b -m "initial release commit"
git show shio-v0.1.0
git push origin shio-v0.1.0
```

Tag `shio-v0.1.0` shows up in the [GitHub remote](https://github.com/RamenDR/ShioRamen/tags) now.

**Comment by hatfieldbrian** [comment]
@tjanssen3 will you please communicate this tag's presence to the fusion team?

**Comment by tjanssen3** [comment]
Left a message in the fusion-metrodr channel about this [here](https://ibm-research.slack.com/archives/C02LYSRJGGG/p1661810853394729)
